Feat : 로그인, 회원가입 기능구현 및 Flex 통일
Hanghae99-DoBlock/FE pull request #17
Opened 2022-11-11 16:52 UTC by Yeonwoo-Ga

2022-11-12 01:36 UTC, NyeongDev commented on src/common/flex/Flex.jsx
>      line-height : ${({lh})=>`${lh}px`};
프리티어 설정 한번 확인 부탁드릴게요!🙏

2022-11-12 01:40 UTC, ose1012 reviewed
다음에는 커밋을 많이 활용해서 잘게 나눠 올려주시면 더 좋을 것 같습니다! 고생 많으셨습니다~😀

2022-11-12 01:41 UTC, NyeongDev commented on src/pages/join/SignInPage.jsx
>  					<path fill-rule="evenodd" clip-rule="evenodd" d="M12 3C7.023 3 3 7.023 3 12C3 16.977 7.023 21 12 21C16.977 21 21 16.977 21 12C21 7.023 16.977 3 12 3ZM12 19.2C8.031 19.2 4.8 15.969 4.8 12C4.8 8.0
svg 태그 따로 분리해주신다고 하셨는데, 이 부분도 정리되고 나서 머지하면 좋을 것 같아요!

2022-11-12 01:43 UTC, NyeongDev requested changes
혹시 joinSlice는 따로 없으실까요..? 파일이 날아간 것 같아요..!

2022-11-12 01:54 UTC, ose1012 commented on src/pages/join/SignUpPage.jsx
>  					<StInfo>올바른 이메일 형식을 입력해주세요</StInfo>
사소한 거긴 한데, 다른 StInfo는 . 이 찍혀있으나 이곳이랑 204줄이 . 이 찍혀있지 않습니다! 하나로 통일해주시면 좋을 것 같아요!

2022-11-12 05:15 UTC, NyeongDev commented
고생하셨습니다!!👍👍🥳 번거로우실 수도 있지만,😭  merge하기 전에 몇 가지만 더 초반에 통일하고 넘어가면 좋을 것 같아요..! 저희가 pull 받은 뒤에 또 각자 수정하는 일이 생기면 여러가지로 복잡해질 것 같아서 지금 조금만 더 같이 이야기해보면 좋겠습니다!

### 이 부분은 반영해주시면 좋을 것 같아요!
- pr 전에, 사용하신 console.log를 지워주시면 저희가 pull 받아서 작업할 때 훨씬 편해질 것 같습니다! (계속 사용하시려면, 주석 처리를 해주셔도 좋을 것 같아요!)
- 탭 간격이 4로 지정되어 있는 파일이 아직 남아있어요!|
- signIn 페이지에 svg 태그가 남아있는데, 깜빡하신 걸까요, 나중에 분리하려고 두신 걸까요?

### 이 부분은 같이 대화해보아요!
- 서버 url을 api 파일 안에 넣어두신 것 같은데, 제 기억으로는 .env 파일에서 관리하는 것으로 대화가 되었던 것 같아요! 혹시 다른 의도가 있으실까요?
- StSvg와 Svg 컴포넌트의 차이점은 무엇인지 궁금합니다!

2022-11-13 08:53 UTC, Yeonwoo-Ga commented
꼼꼼히 봐주셔서 감사합니다 민영님! 답변을 드리자면,

탭간격은 2로 다 조정 다시 해놓았습니다!
svg 태그는 제가 깜빡한것같아 다시 조정해놓았습니다!
콘솔도 전부 지웠구요,

.env에서 서버를 관리하려면 저런 방식으로 꺼내어 쓰는것으로 알고있어서 저렇게 했는데 혹시 문제가 된다면 대화하여 바꾸는 방법도 좋습니다!
StSvg같은경우, 글씨가 길어질수록 아이콘이 작아지는 밀림 현상이 있어, 그부분을 보완하고자 SVG파일을 한번더 감싸준 div입니다. 해당div 사용으로 아이콘이 작아지는 현상이 해결되었답니다!

2022-11-13 09:13 UTC, NyeongDev commented
고생하셨습니다 :)
만들어주신 api.js를 아래처럼 instance를 관리하는 용도로 쓰면 좋을 것 같아요!
나중에 헤더도 같이 이 파일 안에서 관리하면 좋을 것 같습니다.
그래서 redux 폴더 안에 두기보다는 따로 api나 axios라는 폴더를 만들고, instance라는 이름으로 관리하는 건 어떨까요?

- 인스턴스
`const instance = axios.create({
	BASE_URL: process.env.REACT_APP_SERVER,
});
`
- 헤더
`instance.interceptors.request.use(config => {config.headers.authorization = `Bearer ${token}`return config;
});`

2022-11-13 09:15 UTC, NyeongDev approved these changes

2022-11-13 09:24 UTC, ose1012 approved these changes
코드가 훨씬 깔끔해진 것 같아 보기 좋네요~!!! 고생 많으셨습니다😉😉

2022-11-14 01:52 UTC, merged